@startuml
(*)  --> "创建应用"

If "应用类型" then
--> [web/h5] "创建Web应用"
--> "创建实验"

else
--> [ios] "创建ios应用"
--> "创建实验"

else
--> [android] "创建android应用"
--> "创建实验"
Endif

If "实验模式" then
--> [编程] "设置变量"
--> "创建版本"
else
--> [可视化编辑] "视图绑定"
--> "创建版本"
else
--> [多链路合并] "链路匹配（web/h5)"
--> "创建版本"
Endif

--> "创建指标"

if "调试" then
-->[false] "检查集成"
--> ===重复调试===

else
-->[true] "分配流量"

--> "设置受众"

--> "运行实验"


-->(*)
@enduml