package com.tongyl.example.jdemoenummybaits.entity;

import com.tongyl.example.jdemoenummybaits.emum.ComputerState;
import java.io.Serializable;
import java.util.Date;

public class Computer implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_computer.id
     *
     * @mbg.generated Wed Sep 04 11:25:38 GMT+08:00 2019
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_computer.name
     *
     * @mbg.generated Wed Sep 04 11:25:38 GMT+08:00 2019
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_computer.computer_state
     *
     * @mbg.generated Wed Sep 04 11:25:38 GMT+08:00 2019
     */
    private ComputerState computerState;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_computer.create_time
     *
     * @mbg.generated Wed Sep 04 11:25:38 GMT+08:00 2019
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_computer.update_time
     *
     * @mbg.generated Wed Sep 04 11:25:38 GMT+08:00 2019
     */
    private Date updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_computer
     *
     * @mbg.generated Wed Sep 04 11:25:38 GMT+08:00 2019
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_computer.id
     *
     * @return the value of t_computer.id
     *
     * @mbg.generated Wed Sep 04 11:25:38 GMT+08:00 2019
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_computer
     *
     * @mbg.generated Wed Sep 04 11:25:38 GMT+08:00 2019
     */
    public Computer withId(Long id) {
        this.setId(id);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_computer.id
     *
     * @param id the value for t_computer.id
     *
     * @mbg.generated Wed Sep 04 11:25:38 GMT+08:00 2019
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_computer.name
     *
     * @return the value of t_computer.name
     *
     * @mbg.generated Wed Sep 04 11:25:38 GMT+08:00 2019
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_computer
     *
     * @mbg.generated Wed Sep 04 11:25:38 GMT+08:00 2019
     */
    public Computer withName(String name) {
        this.setName(name);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_computer.name
     *
     * @param name the value for t_computer.name
     *
     * @mbg.generated Wed Sep 04 11:25:38 GMT+08:00 2019
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_computer.computer_state
     *
     * @return the value of t_computer.computer_state
     *
     * @mbg.generated Wed Sep 04 11:25:38 GMT+08:00 2019
     */
    public ComputerState getComputerState() {
        return computerState;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_computer
     *
     * @mbg.generated Wed Sep 04 11:25:38 GMT+08:00 2019
     */
    public Computer withComputerState(ComputerState computerState) {
        this.setComputerState(computerState);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_computer.computer_state
     *
     * @param computerState the value for t_computer.computer_state
     *
     * @mbg.generated Wed Sep 04 11:25:38 GMT+08:00 2019
     */
    public void setComputerState(ComputerState computerState) {
        this.computerState = computerState;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_computer.create_time
     *
     * @return the value of t_computer.create_time
     *
     * @mbg.generated Wed Sep 04 11:25:38 GMT+08:00 2019
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_computer
     *
     * @mbg.generated Wed Sep 04 11:25:38 GMT+08:00 2019
     */
    public Computer withCreateTime(Date createTime) {
        this.setCreateTime(createTime);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_computer.create_time
     *
     * @param createTime the value for t_computer.create_time
     *
     * @mbg.generated Wed Sep 04 11:25:38 GMT+08:00 2019
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_computer.update_time
     *
     * @return the value of t_computer.update_time
     *
     * @mbg.generated Wed Sep 04 11:25:38 GMT+08:00 2019
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_computer
     *
     * @mbg.generated Wed Sep 04 11:25:38 GMT+08:00 2019
     */
    public Computer withUpdateTime(Date updateTime) {
        this.setUpdateTime(updateTime);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_computer.update_time
     *
     * @param updateTime the value for t_computer.update_time
     *
     * @mbg.generated Wed Sep 04 11:25:38 GMT+08:00 2019
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_computer
     *
     * @mbg.generated Wed Sep 04 11:25:38 GMT+08:00 2019
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", name=").append(name);
        sb.append(", computerState=").append(computerState);
        sb.append(", createTime=").append(createTime);
        sb.append(", updateTime=").append(updateTime);
        sb.append("]");
        return sb.toString();
    }
}